### ISSUE TITLE
Run components as non-root

### ISSUE THREAD

**Issue by maxbrunet** [thanos-io/kube-thanos#141]
Thanos components run as root by default:

```shell
$ docker run --rm -ti --entrypoint= quay.io/thanos/thanos:v0.14.0 id
uid=0(root) gid=0(root) groups=10(wheel)
```

Pods should probably have a restricted security context, I currently run them with the following (except receive and rule that I do not have):

```yaml
securityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000
```

Do you have an opinion on the uid/gid to use? `65534`/`nobody`/`nogroup` seems popular too, but not everyone thinks this what they should be used for.
