### ISSUE TITLE
Add HOST_IP_ADDRESS env to all containers

### ISSUE THREAD

**Issue by brancz** [thanos-io/kube-thanos#219]
It is not uncommon to deploy tracing agents as daemonsets on every node. The way the tracing libraries are then configured is typically by configuring an environment variable via the Kubernetes downward API. It seems paradox to force this onto downstream users, when the tracing config is already available.

Since it is not harmful to users that don't use this environment variable, I propose we automatically add the `HOST_IP_ADDRESS` environment variable to each Thanos component container, so that for example for tracing purposes the environment variable can be used directly.

cc @metalmatze @kakkoyun

**Comment by metalmatze** [comment]
Yup, sounds good as it doesn't hurt, might be slightly confusing but whatever...
Do you have an example on what we need to add? Or are you asking for consensus to simply add it?

**Comment by brancz** [comment]
Yeah it's pretty straight forward, just:

```yaml
    env:                 
    - name: HOST_IP_ADDRESS
      valueFrom:         
        fieldRef:         
          apiVersion: v1                                                                                               
          fieldPath: status.hostIP  
```

in each container
