### ISSUE TITLE
Cannot connect to prometheus-operated

### ISSUE THREAD

**Issue by polRk** [thanos-io/kube-thanos#272]
I add 
```
        - --store=dnssrv+_grpc._tcp.prometheus-operated.monitoring.svc.cluster.local:10901
```

 into thanos-query-deployment.yaml and it doesn't works, got an error 
 ```
 level=warn ts=2022-04-14T11:54:49.361451651Z caller=endpointset.go:500 component=endpointset msg="update of node failed" err="getting metadata: fallback fetching info from 10.244.0.90:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.244.0.90:10901
 ```

**Comment by polRk** [comment]
I think problem in network policy config (kube-prometheus, prometheus-networkPolicy.yaml)

**Comment by polRk** [comment]
Yep, problem in network policy config
This solved the problem
```
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: thanos-query
    ports:
    - port: 10901
      protocol: TCP
```
