### ISSUE TITLE
Can't save db with objectstorage( Aliyun OSS)

### ISSUE THREAD

**Issue by Cassuis** [thanos-io/kube-thanos#274]
#### My config about objectstorage yam
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: thanos
type: Opaque
stringData:
  thanos.yaml: |-
    type: ALIYUNOSS
    config:
      endpoint: "oss-cn-hangzhou.aliyuncs.com"
      bucket: "my-thanos"
      access_key_id: ""
      access_key_secret: ""
```
#### Question
- i have checked all pod logs, don't have any WARN or ERROR level
- i'm sure objectstoreage key and seecret right
- i can't find any files in my objectstorage(aliyun OSS)
